[package]
name = "rocat"
version = "0.1.3"
authors = ["Blake Mealey <blakemealey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
clap = "2.33.0"
ureq = { version = "2.3.0", features = ["json"] }
