[package]
name = "rocat"
version = "0.2.0"
authors = ["Blake Mealey <blakemealey@gmail.com>"]
edition = "2018"

[dependencies]
serde_yaml = { version = "0.8" }
serde = { version = "1.0", features = ["derive"] }
clap = "2.33.0"
ureq = { version = "2.3.0", features = ["json"] }
glob = "0.3.0"
