# place_file = "dev.rbxl"
[place_files]
main = "dev.rbxl"

[branches."blake/multi-place-projects"]
environment = "staging"
# tag_commit = false
# deploy_mode = "Save"

[environments.staging]
experience_id = 3028808377
# place_id = 7818935418
place_ids = { main = 7818935418 }
