[place_files]
lobby = "project-fixtures/lobby.rbxl"
main = "project-fixtures/main.rbxl"

[branches."blake/multi-place-projects"]
environment = "staging"
# tag_commit = false
# deploy_mode = "Save"

[environments.staging]
experience_id = 3028808377
place_ids = { main = 7818935418, lobby = 7844085774 }
