---
deployments:
  staging:
    - resourceType: experience
      id: singleton
      inputs:
        configuration:
          value:
            genre: Pirate
            playableDevices:
              - computer
            isFriendsOnly: true
            allowPrivateServers: ~
            privateServerPrice: ~
            isForSale: ~
            price: ~
            studioAccessToApisAllowed: true
            permissions: ~
            universeAvatarType: MorphToR15
            universeAnimationType: playerChoice
            universeCollisionType: outerBox
      outputs:
        assetId: 3028808377
    - resourceType: experience_activation
      id: singleton
      inputs:
        experienceId:
          ref:
            - experience
            - singleton
            - assetId
        isActive:
          value: true
      outputs: ~
    - resourceType: experience_icon
      id: game-icon.png
      inputs:
        experienceId:
          ref:
            - experience
            - singleton
            - assetId
        fileHash:
          value: 787f02689d554fd858b6db2e912179524d348a74ba23cffcc9415815e2a27b33
        filePath:
          value: game-icon.png
      outputs:
        assetId: 34487854
    - resourceType: place_configuration
      id: start
      inputs:
        assetId:
          ref:
            - place_file
            - start
            - assetId
        configuration:
          value:
            name: Start name
            description: Start description
            maxPlayerCount: 20
            allowCopying: false
            socialSlotType: Custom
            customSocialSlotCount: 10
        experienceId:
          ref:
            - experience
            - singleton
            - assetId
      outputs: ~
    - resourceType: place_file
      id: start
      inputs:
        deployMode:
          value: publish
        experienceId:
          ref:
            - experience
            - singleton
            - assetId
        fileHash:
          value: 4d3f78c80cbcf5ba8f104555f2bbd9c8f7485d3970de9fbbba5d2c7bc1219ffc
        filePath:
          value: start.rbxlx
      outputs:
        assetId: 7818935418
        version: 16
