name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --locked --verbose
      - name: Run tests
        run: cargo test --locked --verbose
      - name: Run linters
        run: |
          cargo fmt -- --check
          cargo clippy
