name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build release binary
        run: cargo build --verbose --locked --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rocat-win64
          path: target/release/rocat.exe
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Build release binary
        run: |
          source $HOME/.cargo/env
          cargo build --verbose --locked --release
        env:
          OPENSSL_STATIC: 1
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rocat-macos
          path: target/release/rocat
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build release binary
        run: cargo build --locked --verbose --release
        env:
          OPENSSL_STATIC: 1
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rocat-linux
          path: target/release/rocat
  release:
    runs-on: ubuntu-latest
    needs: [windows, macos, linux]
    steps:
      - name: Download win64 binary
        uses: actions/download-artifact@v2
        with:
          name: rocat-win64
          path: binaries
      - name: Download macos binary
        uses: actions/download-artifact@v2
        with:
          name: rocat-macos
          path: binaries
      - name: Download linux binary
        uses: actions/download-artifact@v2
        with:
          name: rocat-linux
          path: binaries
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          # TODO: remove and add body_path once we have an automated release notes generator
          draft: true
          # TODO: remove once we reach a stable version
          prerelease: true
          files: binaries/*
